language: cpp

compiler:
  - gcc
  - clang

before_install:
  - deb http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu precise main 
  - deb-src http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu precise main 
  - sudo apt-get update
  - sudo apt-get install cmake
  - mkdir build
  - cd build
  - cmake ..
  - sudo make
  - cd ..
